## Why we use NumPy ?

### 1. Fast and uses less memory to store data.
### 2. Numpy contains multi-dimensional array and matrix data structures.
### 3. It can be used to perform a number of mathematical operations.


In [192]:
### use ! pip install numpy

In [193]:
# for importng the library
import numpy as np
import numpy

In [194]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [195]:
b = np.array([[1.0,2.0,3.0] , [9.0,8.0,7.0]]) #float values
print(b)

[[1. 2. 3.]
 [9. 8. 7.]]


In [196]:
#getting the dimension
a.ndim

1

In [197]:
b.ndim

2

In [198]:
#getting the shape
a.shape

(3,)

In [199]:
b.shape #(row,columns)

(2, 3)

In [200]:
# getting the size
a.itemsize

4

In [201]:
b.itemsize

8

In [202]:
#getting the type
a.dtype

dtype('int32')

In [203]:
#gettng the total size
a.size*a.itemsize

12

In [204]:
a.nbytes

12

### Accesiing / changing specific elements, rows , columns

In [205]:
a = np.array([[1,2,3,4,5,6] , [7,8,9,10,11,12]])
print(a)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [206]:
#getting the specific the rows and columns   [row,column] or [startindex:endindex:stepsize]
#(index and rows both starting from the zero.)

a[0,5]

6

In [207]:
a[-2 , -1] #in reverse it starts with the -1

6

In [208]:
a[0:,1]

array([2, 8])

In [209]:
a[0:1]

array([[1, 2, 3, 4, 5, 6]])

In [210]:
a[0,1:6:1]

array([2, 3, 4, 5, 6])

In [211]:
a[1,5] = 20
print(a)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 20]]


In [212]:
a[1,3] = 20
print(a)

[[ 1  2  3  4  5  6]
 [ 7  8  9 20 11 20]]


In [213]:
a[:,2] = [1,2]
print(a)

[[ 1  2  1  4  5  6]
 [ 7  8  2 20 11 20]]


In [214]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [215]:
#getting the 4
b[0,1,1]

4

In [216]:
b[:,1,:]

array([[3, 4],
       [7, 8]])

### Intalizing different types of array

In [217]:
#all the zero matrix
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [218]:
#all the ones
np.ones((4,2,2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [219]:
#for other numbers
np.full((3,3),100)

array([[100, 100, 100],
       [100, 100, 100],
       [100, 100, 100]])

In [220]:
np.full_like(a,10)

array([[10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10]])

In [221]:
#random deciamal numbers
np.random.rand(4,2)

array([[0.36695387, 0.80521156],
       [0.26793931, 0.04858066],
       [0.33796727, 0.05713468],
       [0.85977312, 0.07940831]])

In [222]:
np.random.rand(3,4,5)

array([[[0.12621347, 0.01748615, 0.65702642, 0.39051955, 0.94212792],
        [0.20336649, 0.86992657, 0.7298376 , 0.8489655 , 0.42558715],
        [0.15032061, 0.25123363, 0.81946754, 0.6537016 , 0.15274547],
        [0.64490709, 0.93332947, 0.8221334 , 0.17693346, 0.39827965]],

       [[0.49660442, 0.0309694 , 0.82196268, 0.99267124, 0.88750307],
        [0.31200894, 0.38624655, 0.23982112, 0.34221758, 0.73344811],
        [0.14163248, 0.80420854, 0.7177582 , 0.65458571, 0.57899944],
        [0.0760183 , 0.70210687, 0.59813334, 0.54587814, 0.0647072 ]],

       [[0.03871458, 0.88694914, 0.06222913, 0.66436868, 0.21012718],
        [0.62905227, 0.4226735 , 0.72982701, 0.38722076, 0.31028455],
        [0.04230663, 0.29110064, 0.89068908, 0.14996684, 0.11499725],
        [0.45266814, 0.30488783, 0.4884097 , 0.96540266, 0.62865226]]])

In [223]:
np.random.random_sample(a.shape)

array([[0.067645  , 0.74941913, 0.88688848, 0.37729985, 0.42853181,
        0.50971474],
       [0.41364371, 0.67202441, 0.81775738, 0.26340656, 0.23307517,
        0.69843592]])

In [224]:
#random integer value
np.random.randint(20, size = (2,3))

array([[5, 5, 9],
       [1, 6, 6]])

In [225]:
np.random.randint(10,20 , size = (2,3))

array([[15, 19, 17],
       [13, 13, 10]])

In [226]:
#the identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [227]:
#to repeat the array
ar = np.array([[1,2,3,4]])
re = np.repeat(ar , 4 , axis = 1)
print(re)

[[1 1 1 1 2 2 2 2 3 3 3 3 4 4 4 4]]


In [228]:
re = np.repeat(ar , 4 , axis = 0)
print(re)

[[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]


In [229]:
out = np.ones((5,5))
print(out)

z = np.zeros((3,3))
print(z)
z[1,1] = 99
print(z)

out[1:4,1:4] = z
print(out)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[ 0.  0.  0.]
 [ 0. 99.  0.]
 [ 0.  0.  0.]]
[[ 1.  1.  1.  1.  1.]
 [ 1.  0.  0.  0.  1.]
 [ 1.  0. 99.  0.  1.]
 [ 1.  0.  0.  0.  1.]
 [ 1.  1.  1.  1.  1.]]


### Mathematics

In [230]:
a  = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [231]:
a*2

array([2, 4, 6, 8])

In [232]:
a+2

array([3, 4, 5, 6])

In [233]:
a-2

array([-1,  0,  1,  2])

In [234]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [235]:
a += 2    #a=a+2
a

array([3, 4, 5, 6])

In [238]:
b = np.array([0,1,2,3])
c=a+b
c

array([3, 5, 7, 9])

In [241]:
c**2

array([ 9, 25, 49, 81], dtype=int32)

In [242]:
#getting the trigomatrical value
np.sin(c)

array([ 0.14112001, -0.95892427,  0.6569866 ,  0.41211849])

In [243]:
np.tan(c)

array([-0.14254654, -3.38051501,  0.87144798, -0.45231566])

In [249]:
#Linear algebra
a = np.ones([2,3])
print(a)

b = np.full((3,2),3)
print(b)

np.matmul(a,b)   #to multiply the diffrent size of array

[[1. 1. 1.]
 [1. 1. 1.]]
[[3 3]
 [3 3]
 [3 3]]


array([[9., 9.],
       [9., 9.]])

In [253]:
#getting thr determinant
c = np.identity(3)
np.linalg.det(c)

1.0

### Statistics

In [261]:
a = np.array([[1,2,3],[4,5,6,],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [265]:
np.min(a)

1

In [262]:
np.min(a , axis = 1)

array([1, 4, 7])

In [263]:
np.max(a , axis = 0)

array([7, 8, 9])

In [267]:
np.sum(a , axis = 1)

array([ 6, 15, 24])

In [268]:
np.sum(a , axis = 0)

array([12, 15, 18])

## Reorganizing array

In [274]:
before = np.array([[1,2,3,4] , [5,6,7,8]])
before

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [275]:
after = before.reshape((4,2))
print(after)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [276]:
# vertical stacking
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [277]:
#horizontal stacking
h1 = np.array([1,2,3,4])
h2 = np.array([5,6,7,8])

np.hstack([h1,h2])

array([1, 2, 3, 4, 5, 6, 7, 8])

### Miscellaneous

In [289]:
ar = np.random.rand(4,2,5)
ar

array([[[0.46318459, 0.90851528, 0.69039674, 0.66601968, 0.70106342],
        [0.83177133, 0.06082124, 0.81463278, 0.87932292, 0.22947115]],

       [[0.03586642, 0.11553441, 0.66965802, 0.47958734, 0.11061638],
        [0.13705276, 0.82275071, 0.52124761, 0.74224952, 0.70603108]],

       [[0.61029376, 0.52626276, 0.71532768, 0.32652707, 0.19577595],
        [0.19912874, 0.45937141, 0.85880549, 0.42937327, 0.1419449 ]],

       [[0.02743448, 0.54226491, 0.83284186, 0.47286882, 0.16730388],
        [0.13538167, 0.17937424, 0.31691692, 0.80281394, 0.83044512]]])

In [294]:
ar[ar>0.80]

array([0.90851528, 0.83177133, 0.81463278, 0.87932292, 0.82275071,
       0.85880549, 0.83284186, 0.80281394, 0.83044512])